package com.bsamaripa.euler

/**
  * Problem 2
  *
  * Even Fibonacci numbers
  *
  * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  * By starting with 1 and 2, the first 10 terms will be:
  * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  *
  * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  * find the sum of the even-valued terms.
  *
  */

class Problem002 extends EulerSpec {
  def sumEvenFib(n: Int): Long = {
    0L // TODO: Implementation
  }

  test("Even Fibonacci numbers") {
    sumEvenFib(2) shouldEqual 2L
    sumEvenFib(4) shouldEqual 7L
    sumEvenFib(6) shouldEqual 20L
    sumEvenFib(???) shouldEqual __ // TODO: Fix Test
  }
}
